version: '2'

services:
  minio1:
    image: minio/minio
    volumes:
    - MINIO1:/export
    ports:
    - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: ACCESS_KEY
      MINIO_SECRET_KEY: SECRET_KEY
    command: server http://minio{1...4}/export

  minio2:
    image: minio/minio
    volumes:
    - MINIO2:/export
    ports:
    - "9002:9000"
    environment:
      MINIO_ACCESS_KEY: ACCESS_KEY
      MINIO_SECRET_KEY: SECRET_KEY
    command: server http://minio{1...4}/export

  minio3:
    image: minio/minio
    volumes:
    - MINIO3:/export
    ports:
    - "9003:9000"
    environment:
      MINIO_ACCESS_KEY: ACCESS_KEY
      MINIO_SECRET_KEY: SECRET_KEY
    command: server http://minio{1...4}/export

  minio4:
    image: minio/minio
    volumes:
    - MINIO4:/export
    ports:
    - "9004:9000"
    environment:
      MINIO_ACCESS_KEY: ACCESS_KEY
      MINIO_SECRET_KEY: SECRET_KEY
    command: server http://minio{1...4}/export

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  MINIO1:
  MINIO2:
  MINIO3:
  MINIO4:
